service: todo-api # NOTE: update this with your service name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
#  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs6.10
functions:
  app:
    handler: src/app.handler 
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      
